version: 0.2
env:
  variables:
    OS: "windows_2016"
  exported-variables:
    - OS
    - CODEBUILD_BUILD_ID
phases:
  pre_build:
    commands:
      - echo "Downloading and installing packer"
      - ls
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip && unzip -o packer.zip
      - echo "Executing packer template validation"
      - ./packer validate -var-file="./packer/vars/${OS}_vars.json" ./packer/${OS}.json
  build:
    commands:
      - echo "Executing packer build"
      - ./packer build -color=false -var-file="./packer/vars/${OS}_vars.json" ./packer/${OS}.json | tee packer.log
  post_build:
    commands:
      - test -f ${OS}_manifest.json || exit 1
      - cat ${OS}_manifest.json
      - echo "Build completed on $(date)"