version: 0.2
phases:
  pre_build:
    commands:
      - echo "Downloading and installing packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip && unzip packer.zip
      - echo "Executing packer template validation"
      - echo "Validating packer template"
      - ./packer validate -var-file="kali_vars.json" kali.json
      #- ./packer validate -var-file="windows_2016_vars.json" windows_2016.json
  build:
    commands:
      - echo "Executing packer build"
      - ./packer build -color=false -var-file="kali_vars.json" kali.json | tee packer.log
      #- ./packer build -color=false -var-file="windows_2016_vars.json" windows_2016.json | tee packer.log
  post_build:
    commands:
      #- test -f win16_manifest.json || exit 1
      #- cat win16_manifest.json
      #- AMI_ID=$(cut -d':' -f2 <<<"$(jq -r '.builds[0].artifact_id' < win16_manifest.json)")
      - test -f kali_manifest.json || exit 1
      - cat kali_manifest.json
      - AMI_ID=$(cut -d':' -f2 <<<"$(jq -r '.builds[0].artifact_id' < kali_manifest.json)")
      - test "$AMI_ID" != "" && test "$AMI_ID" != "null" || exit 1
      - >-
        aws ssm put-parameter --cli-input-json
        '{"Type": "String", "Name": "/ami/windows_2016/id", "Value": "'"$AMI_ID"'", "Overwrite": true}'
      - echo "AMI ID $AMI_ID"
      - echo "Build completed on $(date)"
