version: 0.2
phases:
  pre_build:
    commands:
      - echo "Downloading and installing packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip && unzip packer.zip
      - echo "Executing packer template validation"
      - echo "Validating packer template"
      - ./packer validate -var-file="kali_vars.json" kali.json
  build:
    commands:
      - echo "Executing packer build"
      - ./packer build -color=false -var-file="kali_vars.json" kali.json | tee packer.log
  post_build:
    commands:
      - test -f kali_manifest.json || exit 1
      - cat kali_manifest.json
      - echo "Build completed on $(date)"
